services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart:
      always
  smtp:
    image: maildev/maildev:latest
    ports:
      - "1080:1080"
      - "1025:1025"
    healthcheck:
      test: [ "CMD-SHELL", "echo ok" ]
volumes:
  postgres_data:
